### PR TITLE
Update control.lua

### PR DESCRIPTION
**Pull request by Simcra**
fixed a crash when more than one digging robot deployment center is placed and the wall is destroyed before the digging robot gets to it.

### CODE REVIEW

**Comment by stanfear** [comment]
thank you for trying to help, but all the changes you made are useless, in the trigger event, in the area where the wall is destroyed, we already have done the test you added, and on the other methods, the same is true

**Comment by stanfear** [comment]
also, when does the crash happens ? 
is it really a crash ? or just a bug ?

**Comment by Simcra** [comment]
When you place more than one robot digging deployment center near each other and have them both running, both robots attack the same tile and after one destroys it, it crashes the game.

**Comment by Simcra** [comment]
Also, the digging robot planner doesn't let you select the first tile as a cave wall, it only works if you select a out-of-map tile.

**Comment by Simcra** [comment]
Totally not related question, but are the robots going to act like this when they are done? it's awfully expensive and slow.

**Comment by Simcra** [comment]
also, another small bug: when you place the robot drilling center flush against a wall the robots will spawn in an awkward place and become stuck disallowing the process to begin.

**Comment by stanfear** [comment]
I never manages to reproduce the crash ... when two start atacking the same wall, one dies, the other starts wandering about, I know, this is supposed to be fixed soon, there is definetly an issue with the planner, alkthough it is not exactly what you said (you can select starting on any tile)

As for the way they work, it is indeed not the place to talk about this but, I intend to do some small modifications just not sure what yet

**Comment by Simcra** [comment]
Yeah sorry, just like I said on the forums I really appreciate your work. I want to help in any way that I can.

**Comment by Simcra** [comment]
Ok, so I managed to get it working properly in both singleplayer and multiplayer, I'm going to upload my changes to my fork, would you like me to put another pull request?

**Comment by stanfear** [comment]
Hey, I wanted to say, sorry if I appeared harsh on the first post,
I did not mean to be...

also, the way the robots work, do you mean how they behave or how the algorithme behaves ? 
Just so you know, speeding up the code is what I'm currently working on (adding cache is one of the things I plan to do) 
as to the digging behaviour, that's what I initially understood, so ... I do intend to make small tweaks (still not sure which though)

**Pull request closed without merging**
