### PR TITLE
fixed bugs/crashes with the digging robot system

### PR DESCRIPTION
**Pull request by Simcra**
Updated digging robot system to use UnitGroup, Robots will now self-destruct when they decide to randomly wander, fixed a few minor bugs with the selection marker, added some extra data validation, fixed a crash caused by the mobile borer when using digging robots.

Note: when robots finish digging the area selected, the server lags horrendously (before and after these patches) there is also a bug when the robots cross over conveyor belts which causes them to be destroyed.

### CODE REVIEW

**Comment by stanfear** [comment]
just wait before you do any more changes, I'm working on it too, 
just for now I don't need help, I'd be glad to tell you when I'll need it, 

but for now, don't spend time working on something I'm already working on

(I'll still check your changes and use them if needed)
I currently have a non pushed change on my computer fixing the multi-deployment center bug

**Comment by stanfear** [comment]
hey, just sorry again for being harsh, I had spent some time on making several deployment center work and you worked on the same thing... 

I wouldn't refuse some help, just before, ask me if what you want to do is not already worked on!
it would save us both some time

**Comment by Simcra** [comment]
It's cool, I understand and also would like to say sorry if I sounded like an ass with what I said. It would be good to push changes more often so that it is easier for people to work collaboratively with you, regardless if it's me or someone else. Additionally, is there some way that I can contact you other than GitHub which would result in a bit less of a delayed reply? Would like to see where you're up to with the diggers. Finally, there is a bug with the underground fluid tanks and conveyors in multiplayer that causes a crash, your message function in lua.lib at line 186 errors out, I'm sure you'll be able to fix this quite easily though. I have another change I will push shortly fixing a bug with the item elevators being placed incorrectly on the top-most surface.

**Comment by stanfear** [comment]
sure, I have skype, you can find me using the profile page on the forums (not sure putting it here is a good idea)

**Comment by Simcra** [comment]
ok thanks

**Pull request closed without merging**
